name: esp

on:
  push:
    branches: [ master ]
    # TODO: Uncomment
    # paths:
    #   - 'crates/ascot-esp32c3/**'
  pull_request:
    branches: [ master ]
    # TODO: Uncomment
    # paths:
    #   - 'crates/ascot-esp32c3/**'

jobs:
  rustfmt-clippy-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            flex bison gperf \
            cmake ninja-build libffi-dev libssl-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src, rustfmt, clippy

      - name: Install ldproxy
        run: |
          cargo install ldproxy

      # - name: Run rustfmt
      #   working-directory: crates/ascot-esp32c3
      #   run: cargo fmt --all -- --check --verbose

      # - name: Run cargo clippy
      #   working-directory: crates/ascot-esp32c3
      #   run: cargo clippy --all-targets -- -D warnings

      - name: Build
        working-directory: crates/ascot-esp32c3
        run: cargo build --verbose

      - name: Build light
        working-directory: crates/ascot-esp32c3/examples/light
        run: |
          sed -e 's/your Wi-Fi SSID/ssid/' \
              -e 's/your Wi-Fi password/password/' \
              -e 's/your hostname/hostname/' \
              -e 's/your discovery service/service/' \
              cfg.toml.example > cfg.toml
          cargo build --verbose
